// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/maidol/kratos-layout/internal/biz"
	"github.com/maidol/kratos-layout/internal/conf"
	"github.com/maidol/kratos-layout/internal/data"
	"github.com/maidol/kratos-layout/internal/server"
	"github.com/maidol/kratos-layout/internal/service"
	"github.com/prometheus/client_golang/prometheus"
	"go.opentelemetry.io/otel/sdk/trace"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider, histogramVec *prometheus.HistogramVec, counterVec *prometheus.CounterVec) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	greeterClient := data.NewHelloServiceClient(discovery, tracerProvider)
	dataData, cleanup, err := data.NewData(confData, logger, greeterClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger, tracerProvider, histogramVec, counterVec)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, tracerProvider, histogramVec, counterVec)
	registrar := server.NewRegistrar(registry, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
